/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanagementsystem;

import java.awt.Frame;


public class CreateEventFrame extends java.awt.Frame {

    /**
     * Creates new form CreateEventFrame
     */
    public CreateEventFrame() {
        initComponents();
    }

    public String name ;
    public String coord ;
    public String venue ;
    public String time ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        event_name_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        event_coord_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        submit_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        status_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        venue_filed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        time_filed = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Event Name");
        jPanel1.add(jLabel1);

        event_name_field.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(event_name_field);

        jLabel4.setText("Event Coordinator");
        jPanel1.add(jLabel4);

        event_coord_field.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(event_coord_field);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(submit_button);

        home_button.setText("Home");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(home_button);

        status_label.setText("Status : ");
        jPanel2.add(status_label);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel2.setText("Venue");
        jPanel3.add(jLabel2);

        venue_filed.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(venue_filed);

        jLabel3.setText("Time");
        jPanel3.add(jLabel3);

        time_filed.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(time_filed);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        Frame f1 = new MainPage(name,coord,venue,time);
        f1.pack();
        f1.setVisible(true);        
    }//GEN-LAST:event_home_buttonActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        name=event_name_field.getText();
        coord=event_coord_field.getText();
        venue=venue_filed.getText();
        time=time_filed.getText();
        status_label.setText(name + " creation:SUCCESS");
        event_name_field.setText("");
        event_coord_field.setText("");
        venue_filed.setText("");
        time_filed.setText("");
    }//GEN-LAST:event_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEventFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField event_coord_field;
    private javax.swing.JTextField event_name_field;
    private javax.swing.JButton home_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel status_label;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextField time_filed;
    private javax.swing.JTextField venue_filed;
    // End of variables declaration//GEN-END:variables
}
