/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanagementsystem;

import java.awt.Frame;


public class MainPage extends java.awt.Frame {

    public String name ;
    public String coord ;
    public String venue ;
    public String time ;
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    public MainPage(String name, String coord, String venue, String time){
        initComponents();
        this.name=name;
        this.coord=coord;
        this.venue=venue;
        this.time=time;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_event_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        register_event_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        show_events_button = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        create_event_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        create_event_button.setText("Create Event");
        create_event_button.setMaximumSize(new java.awt.Dimension(300, 100));
        create_event_button.setPreferredSize(new java.awt.Dimension(300, 100));
        create_event_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_event_buttonActionPerformed(evt);
            }
        });
        add(create_event_button, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        register_event_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        register_event_button.setText("Register Event");
        register_event_button.setPreferredSize(new java.awt.Dimension(300, 100));
        register_event_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_event_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_event_button, java.awt.BorderLayout.PAGE_START);

        logout_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout_button.setText("Logout");
        logout_button.setPreferredSize(new java.awt.Dimension(300, 100));
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logout_button, java.awt.BorderLayout.PAGE_END);

        show_events_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_events_button.setText("Show Events");
        show_events_button.setPreferredSize(new java.awt.Dimension(300, 100));
        show_events_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_events_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(show_events_button, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void create_event_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_event_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new CreateEventFrame();
        f1.pack();
        f1.setVisible(true);
        
    }//GEN-LAST:event_create_event_buttonActionPerformed

    private void register_event_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_event_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new RegisterEvent();
        f1.pack();
        f1.setVisible(true);
                
    }//GEN-LAST:event_register_event_buttonActionPerformed

    private void show_events_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_events_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new ShowEventFrame(name,coord,venue,time);
        f1.pack();
        f1.setVisible(true);
                
    }//GEN-LAST:event_show_events_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new LoginFrame();
        f1.pack();
        f1.setVisible(true);
        f1.setSize(400,400);        
    }//GEN-LAST:event_logout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_event_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton register_event_button;
    private javax.swing.JButton show_events_button;
    // End of variables declaration//GEN-END:variables
}
