/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanagementsystem;

import java.awt.Frame;


public class RegisterEvent extends java.awt.Frame {

    /**
     * Creates new form RegisterEvent
     */
    public RegisterEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reg_num_filed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stud_name_filed = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        event_name_field = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Register Number");
        jPanel1.add(jLabel1);

        reg_num_filed.setMinimumSize(new java.awt.Dimension(100, 20));
        reg_num_filed.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(reg_num_filed);

        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3);

        stud_name_filed.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(stud_name_filed);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        register_button.setText("Register");
        jPanel2.add(register_button);

        home_button.setText("Home");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(home_button);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel2.setText("Event-Name");
        jPanel3.add(jLabel2);

        event_name_field.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(event_name_field);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new MainPage();
        f1.pack();
        f1.setVisible(true);        
    }//GEN-LAST:event_home_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterEvent().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField event_name_field;
    private javax.swing.JButton home_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField reg_num_filed;
    private javax.swing.JButton register_button;
    private javax.swing.JTextField stud_name_filed;
    // End of variables declaration//GEN-END:variables
}
