/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanagementsystem;

import java.awt.Frame;


public class ShowEventFrame extends java.awt.Frame {
    public String name ;
    public String coord ;
    public String venue ;
    public String time ;
    /**
     * Creates new form ShowEventFrame
     */
    public ShowEventFrame() {
        initComponents();
    }

    public ShowEventFrame(String name, String coord, String venue,String time){
        initComponents();
        this.name=name;
        this.coord=coord;
        this.venue=venue;
        this.time=time;
        
        name_filed.requestFocus();
        name_filed.append(name);
        name_filed.append("\n");
        
        venue_filed.requestFocus();
        venue_filed.append(venue);
        venue_filed.append("\n");
        
        time_filed.requestFocus();
        time_filed.append(time);
        time_filed.append("\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        home_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        name_filed = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        venue_filed = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        time_filed = new javax.swing.JTextArea();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Event-Name");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Event-Venue");
        jPanel1.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Event-Time");
        jPanel1.add(jLabel3);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        home_button.setText("Home");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(home_button);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        name_filed.setColumns(20);
        name_filed.setRows(5);
        jScrollPane5.setViewportView(name_filed);

        jPanel4.add(jScrollPane5);

        venue_filed.setColumns(20);
        venue_filed.setRows(5);
        jScrollPane6.setViewportView(venue_filed);

        jPanel4.add(jScrollPane6);

        time_filed.setColumns(20);
        time_filed.setRows(5);
        jScrollPane7.setViewportView(time_filed);

        jPanel4.add(jScrollPane7);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Frame f1 = new MainPage();
        f1.pack();
        f1.setVisible(true);        
    }//GEN-LAST:event_home_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowEventFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea name_filed;
    private javax.swing.JTextArea time_filed;
    private javax.swing.JTextArea venue_filed;
    // End of variables declaration//GEN-END:variables
}
